version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
